config/routes.rb
Rails.application.routes.draw do
  resources :invitations do
  end
  resources :markers do
    resources :pictures
    get :autocomplete_user_email, :on => :collection
    member do
      get 'invite'
    end

    collection do
      get 'partial'
      get 'approve_member'
      get 'reject_member'
    end
  end
  resources :tracks, controller: 'markers'
  #get 'template/index'

  resources :template, only: [:index]
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    :registrations => "users/registrations",
                                    :omniauth_callbacks => "users/omniauth_callbacks"}
  #devise_for :users
  resources :people
  root :to => 'template#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/marker.rb
class Marker
  include Mongoid::Document
  include Mongoid::Paperclip
  embeds_many :pictures, :cascade_callbacks => true
  has_and_belongs_to_many :users
  has_many :invitations
  accepts_nested_attributes_for :pictures
  #field :name, type: String
  #field :locations
  has_mongoid_attached_file :video, :styles => {
    :medium => { :geometry => "320x280", :format => 'mp4' },
  }, processors: [:transcoder] 
  validates_attachment_content_type :video, :content_type => ['video/x-flv','video/mp4','video/mpeg','video/webm','video/avi','video/ogg','video/x-divx','video/divx', 'video/x-msvideo'] #["video/mp4"] 

  
  has_mongoid_attached_file :pdf
  validates_attachment_content_type :pdf, :content_type => ['application/pdf', 'application/msword', 'text/plain']


  field :from_latitude, type: :float
  field :from_longitude, type: :float
  field :to_latitude, type: :float
  field :to_longitude, type: :float
  field :location_from
  field :location_to
  field :departure_date, type: :date
  field :begin_at, type: :time
  field :end_at, type: :time
  field :created_by, type: :integer
  field :invitation_sent, type: :integer
  field :pending, type: Array, default: []
  field :active, type: Array, default: []
  # validates :from_latitude, presence: true
  # validates :from_longitude, presence: true
  # validates :to_latitude, presence: true
  # validates :to_longitude, presence: true
  # validates :location_from, presence: true
  # validates :location_to, presence: true

  before_destroy :remove_trip_id_from_all_users


  #validates :name, :presence => true
  #validates :latitude, :presence => true
  #validates :longitude, :presence => true
  #field :coordinates, :type => Array
  #field :address
  #include Geocoder::Model::Mongoid
	#geocoded_by :name               # can also be an IP address
	#after_validation :geocode 
  #geocoded_by :name
  #after_validation :name, :if => :name_changed?

  protected

  def remove_trip_id_from_all_users

    self.users.each do |user|
      user.marker_ids.delete(self.id)
      user.save!
    end
  end

  def join_marker
    
  end

end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  skip_before_action :verify_authenticity_token
	before_action :authenticate_user!
  load_and_authorize_resource
  autocomplete :user, :email

	def index

      #@marker = Marker.new

      @invitation = Invitation.new
      if current_user.roles.first.name == "admin"
        @markers = Marker.all.to_a
      else
        @markers = current_user.markers
      end
      # @q = Marker.ransack(params[:q])
      # @markers = @q.result

      # if current_user.roles.first.name != "admin"
      #   @markers = @markers.where(user_ids: current_user.id).to_a
      # else
      #   @markers = @markers.to_a
      # end

      if session[:code].present?
        trip = Marker.where(id: session[:code]).first
        unless current_user.markers.include? :trip
           current_user.markers << trip
            unless trip.pending.include? current_user.id
              trip.pending << current_user.id
              trip.save!
            end
            session[:code] = ''
        end
      end
  end


  def new

    @marker = Marker.new
    @marker.pictures.build
    respond_to do |format|
      format.js{}
    end
  end

  def show

    @users = Marker.users.where(id: current_user.id)
    respond_to do |format|
      format.js {}
    end
  end

  def edit
    @marker = Marker.find(params[:id])
    puts 'Inside Edit'
    puts @marker.inspect

    respond_to do |format|
      format.js{}
    end
  end

  def update

    puts 'Inside Update!'
    puts '****************'

   @marker = Marker.find(params[:id])

    respond_to do |format|
      if @marker.update_attributes!(marker_params)
        puts '****************HERE*****************'
        format.js{flash[:notice] = "Trip has been Updated!"}
      else
        render :edit
      end
    end
  end

  def approve_member

    trip = Marker.find(params[:trip][:trip_id])
    user_id = User.find_by(email: params[:trip][:email]).id

    trip.pending.delete(user_id)
    trip.active << user_id
    trip.save!
  end

  def reject_member

    puts 'Inside Reject Member function'

    trip = Marker.find(params[:trip][:trip_id])
    user = User.find_by(email: params[:trip][:email])
    trip.pending.delete(user.id)
    trip.user_ids.delete(user.id)
    user.marker_ids.delete(trip.id)
    trip.save!
    user.save!

  end

	def create

    @marker = Marker.new(marker_params)
    @marker.user_ids << current_user.id
    respond_to do |format|
      if @marker.save!
        format.html {redirect_to tracks_path}
        format.js{flash[:notice] = "Trip has been Created!"}
      else
        puts '********************Errors******************'
        puts @marker.error.full_messages
        render :new
      end
    end
	end

  def destroy
    @record = Marker.find(params[:id])
    @deleted_record = @record
    @record.destroy
    respond_to do |format|
      format.js {flash[:notice] = "Trip has been Deleted!"}
    end
  end

  def invite

    @trip = Marker.find(params[:id])
    @start = @trip.location_from.split(',')
    @start = @start[-2] + @start[-1].to_s
    @end = @trip.location_to.split(',')
    @end = @end[-2] + @end[-1].to_s
    if Invitation.where(user_id: current_user.id, marker_id: @trip.id).present?
       @invitation = Invitation.find_by(user_id: current_user.id, marker_id: @trip.id)
    else
       @invitation = Invitation.new
    end

    respond_to do |format|
      format.js {}
    end
  end

  # def partial
  #
  #   @flag = params[:flag]
  #   respond_to do |format|
  #     format.js {}
  #   end
  # end

	private

	def marker_params
		params.require(:marker).permit(:from_latitude,:from_longitude,:to_latitude,:to_longitude,:location_from,
                                   :location_to,:user_ids, :departure_date, :begin_at, :end_at, :video, :pdf, :pending => [],
                                   pictures_attributes: [:avatar,:_destroy, :id])
	end

end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_form.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Siimple - Free Bootstrap 3 Landing Page</title>
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">Siimple</a>
        </div>
        <div class="navbar-collapse collapse">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path%></li>
            </ul>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </div>

  <div id="header">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">

          <h1>New Location</h1>

            <%= form_with(model: location, local: true) do |form| %>
              <% if location.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(location.errors.count, "error") %> prohibited this person from being saved:</h2>

                  <ul>
                  <% location.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field">
                <%= form.label :name %><br />
                <%= form.text_field :name, class:'text-field-design', autofocus: true %>
              </div>
              <div class="field">
                <%= form.label :latitude %><br />
                <%= form.text_field :latitude, class:'text-field-design', autofocus: true %>
              </div>
              <div class="field">
                <%= form.label :longitude %><br />
                <%= form.text_field :longitude, class:'text-field-design', autofocus: true %>
              </div>

              <div class="actions">
                <%= form.submit %>
              </div>
            <% end %>
             <div style='width: 50px;'>
            <div id="map" style='width: 300px; height: 250px;'></div>
          </div> 
          <!--%= render "devise/shared/links" %-->      
        </div>
        <div class="col-lg-4 col-lg-offset-2">
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>         
            <!-- slides -->
            <div class="carousel-inner">
            <div class="item active">
              <%= image_tag("slide1.png" , alt:"image") %>
            </div>
            <div class="item">
              <%= image_tag("slide2.png" , alt:"image") %>
            </div>
            <div class="item">
              <%= image_tag("slide3.png" , alt:"image") %>
            </div>
            </div>
          </div>    
        </div>
        
      </div>
    </div>
  </div>
  <div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
              <p class="copyright">&copy; Siimple Theme</p>
      </div>
            <div class="col-md-6">
                <div class="credits">
                    <a href="https://bootstrapmade.com/free-business-bootstrap-themes-website-templates/">Business Bootstrap Themes</a> by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
    </div>    
  </div>  
  </div>


    
</body>
</html>

app/views/markers/_invitation.html.erb
<div>
  <h3> Sending Invitation from <%= @start %> to <%= @end %>  </h3>
  <%= form_for(invitation, remote: true) do |f| %>
      <div class="row">
        <div class="col-md-2">
          To:
        </div>
        <div class="col-md-10">
          <%#= f.text_field :send_to, class: 'text-field-design', value: '' %>
          <%= f.autocomplete_field :send_to,  autocomplete_user_email_markers_path, value: [], 'data-delimiter' => ',', :multiple => true %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          Body:
        </div>
        <div class="col-md-10">
          <%= f.text_area :email_body, class:"text-area-design", value: 'I am inviting you to join the trip. You can join it by clicking on the link below' %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :marker_id,value: trip.id %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-md-offset-4">
          <%= f.submit 'Invite' , class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
  <% end %>
</div>


<script type="text/javascript">
    $('.email-template-load').show();
  $("form").submit(function(e) {
        //$('.flash-message').text("Email has been Sent!")
        $('.flash-message').html("<div class='alert alert-success %> alert-dismissible' role='alert'><button class='close' data-dismiss='alert'>×</button><%= "Invitation Email has been sent!" %></div>");
        $('.email-template-load').hide();
    });

</script>

app/views/markers/_modal.html.erb
<!--button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal1">Open Modal</button-->

<!-- Modal -->
<!--div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Modal Header</h4>
</div>
<div class="modal-body">
  <p>Some text in the modal.</p>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div-->

<div class="form-group">
  <div class="row">
    <div class="col-md-2">
      Starting From:
    </div>
    <div class="col-md-3">
      <input id='gmaps-input-address-from' class='form-control' placeholder='Start typing a place name...' type='text' />
    </div>
    <div class="col-md-2">
      Destination:
    </div>
    <div class="col-md-3">
      <input id='gmaps-input-address-to' class='form-control' placeholder='Start typing a place name...' type='text' />
    </div>
  </div>

  <%= nested_form_for(@marker, html: { multipart: true }, remote: true) do |f| %>
      <%= f.hidden_field :from_latitude, id:"location-latitude1" %>
      <%= f.hidden_field :from_longitude, id:"location-longitude1" %>
      <%= f.hidden_field :to_latitude, id:"location-latitude2" %>
      <%= f.hidden_field :to_longitude, id:"location-longitude2" %>
      <%= f.hidden_field :location_from, id:"location-from" %>
      <%= f.hidden_field :location_to, id:"location-to" %>
      <div class="row row-designing">
        <div class="col-md-2">
          Departure Date:
        </div>
        <div class="col-md-3">
          <%= f.text_field :departure_date, id:'datepicker', value: @marker.departure_date.present? ? @marker.departure_date.strftime('%d-%m-%Y') : ''  %>
        </div>
        <div class="col-md-2">
          Begin At:
        </div>
        <div class="col-md-3">
          <%= f.text_field :begin_at, class: 'timepicker1', :value => Time.now.strftime("%T")  %>
        </div>
        <div class="col-md-2">
          <%= f.file_field :video %>
        </div>
      </div>
      <div class="row row-designing">
        <div class="col-md-2">
          End At:
        </div>
        <div class="col-md-3">
          <%= f.text_field :end_at, class: 'timepicker1', :value => Time.now.strftime("%T") %>
        </div>
        <div class="col-md-3">
          <%= f.fields_for :pictures do |picture| %>
              <%= picture.file_field :avatar, type: :file%>
              <%= picture.link_to_remove "Remove this picture" %>
          <% end %>
          <p><%= f.link_to_add "Add a picture", :pictures %></p>
        </div>

        <div class="col-md-2">
          <%= f.file_field :pdf %>
        </div>

        <div class="col-md-3 col-md-offset-2">
          <%= f.submit 'Add Trip' , class: "btn btn-primary" %>
        </div>
      </div>
  <% end %>
  <!--input type="text", id="datetimepicker1" />
  <button type="button", id="submit-modal" > Submit </button-->
</div>

<script type="text/javascript">
  $(function () {
  $('#datepicker').datepicker({
      dateFormat: 'dd-mm-yy'

  });
  $('.timepicker1').timepicker({ 'scrollDefaultNow': true });
  
  });

</script>

app/views/markers/_new_trip.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Modal header</h3>
</div>
<div class="modal-body">
  **here comes whatever you want to show!**
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <button class="btn btn-primary">Save changes</button>
</div>

app/views/markers/_partial.html.erb
<tr class="row" id=<%= route.id %> >
	<td class="col-md-4"><%= route.location_from %> </td>
	<td class="col-md-4"><%= route.location_to %></td>
	<td class="col-md-4">
    <a href='#', onclick="event.preventDefault(); return false;",  class="load-location link-designing"
       data-location_from_latitude="<%= route[:from_latitude] %>"
       data-location_from_longitude="<%= route[:from_longitude] %>"
       data-location_to_latitude="<%= route[:to_latitude] %>"
       data-location_to_longitude="<%= route[:to_longitude]%>" data-pending-members="<%= User.find(route.pending).pluck(:email) %>" data-active-members="<%= User.find(route.active).pluck(:email) %>" data-trip="<%= route.id %>" data-role="<%= current_user.roles.first.name %>" data-images="<%= picture_urls %>" >
		  <i class="glyphicon glyphicon-asterisk"></i>
	  </a>
    <%= link_to edit_marker_path(route), data: {target: '#myModal',toggle: 'modal'}, class: 'link-designing', remote: :true do %>
        <i class="glyphicon glyphicon-edit"></i>
    <% end %>

    <%= link_to  marker_path(route), class:'link-designing', method: :delete, remote: :true do %>
      <i class="glyphicon glyphicon-remove"></i>
    <% end %>
    <%= link_to 'Invite', invite_marker_path(route.id), class:"link-designing", remote:true %>
  </td>
</tr>


<!--div class="location-information" id=< route[:id] %> >
	< route[:location_from] %>
	< route[:location_to] %>
	<div class="position-align">
		<button class="load-location btn btn-primary" data-location_from_latitude="< route[:from_latitude] %>" data-location_from_longitude="< route[:from_longitude] %>" data-location_to_latitude="< route[:to_latitude] %>" data-location_to_longitude="< route[:to_longitude]%>" >Load Location</button>
		< link_to  "Delete Location", marker_path(route), method: :delete, remote: :true, class: "btn btn-primary" %>
	</div>
</div-->

app/views/markers/_partial1.html.erb
<div class="form-group">
  <div class="row">
    <div class="col-md-2">
      Starting From:
    </div>
    <!--div class="col-md-3">
      <input id='gmaps-input1-address-from' class='form-control' placeholder='Start typing a place name...' type='text' />
    </div>
    <div class="col-md-2">
      Destination:
    </div>
    <div class="col-md-3">
      <input id='gmaps-input1-address-to' class='form-control' placeholder='Start typing a place name...' type='text' />
    </div>
  </div-->

  <input type="text", id="datetimepicker1" />
  <button type="button", id= <%= @flag == 'date-from' ? 'submit-modal' : 'hello'  %> > Submit </button>


</div>


  <!--div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div-->

app/views/markers/create.js.erb
$('.append-row').append('<%= escape_javascript(render partial: "partial", locals:{ route: @marker, picture_urls: @marker.pictures }) %>');
$('.flash-message').html("<div class='alert alert-success %> alert-dismissible' role='alert'><button class='close' data-dismiss='alert'>×</button><%= flash[:notice] %></div>");

app/views/markers/index.html.erb
<!DOCTYPE html>
<head>
  <meta charset='utf-8'>
  <title>rjshade/gmaps-autocomplete @ GitHub</title>
  <title>Google Maps and jqueryUI</title>

  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand">
        Join Trip
      </div>
      <!--a class="navbar-brand" href="#">WebSiteName</a-->
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><div class="navbar-brand"><%= current_user.name.titleize %></div> </li>
      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
    </ul>
  </div>
</nav>


<div class="container container-designing">
  <div class="flash-message">
  </div>
  <!--div class="image-display"-->
    <!--% if current_user.avatar.present? %-->
      <!--%= image_tag current_user.avatar.url %-->
    <!--% end %-->
  <!-- /div-->

  <!--div class="modal-popup">

    <div class="modal" id="myModal1" role="dialog">
      <div class="modal-dialog"-->

        <!-- Modal content-->
        <!--div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Add trip</h4>
          </div>
          <div class="modal-body edit-trip-body">
          </div>
        </div>
      </div>
    </div>
  </div-->



  <div class="modal-popup">
    <div class="modal" id="myModal" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Add trip</h4>
          </div>
          <div class="modal-body">
          </div>
          <!--div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div-->
        </div>
      </div>
    </div>
  </div>


  <!--%= link_to 'Load Partial', partial_markers_path(flag: 'date-to'), {:remote => true,"data-toggle": "modal", "data-target": "#myModal"} %-->

  <div class="row">
    <div class="col-sm-3">
      <h3 class="text-info">Trips History </h3>
    </div>
    <div class="col-sm-2 create-trip-button">
      <!--button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#myModal">Create trip</button-->
      <%= link_to 'Create Trip', new_marker_path, class:"btn btn-info btn-md", data: {target: '#myModal',toggle: 'modal'},remote: :true %>
    </div>
  </div>
  <div class="row main-div">
    <div class="col-md-6">
      <table class="table table-striped">
        <thead>
        <tr class="row">
          <th class="col-sm-4">Starting Location</th>
          <th class="col-sm-4">Ending Location</th>
          <th class="col-sm-offset-1 col-sm-3">Actions</th>
        </tr>
        </thead>
        <tbody class="append-row">
        <%- @markers.each do |location| %>
            <% array = [] %>
            <% location.pictures.each do |picture| %>
              <% array << picture.avatar.url %> 
            <% end %>
            <% puts '@@@@@@@@@@@@@@@@@@@@@@@@@@@2'%>
            <% puts array %>
            <%= render 'partial', route: location, picture_urls: array %>
        <% end %>
        </tbody>
      </table>
      <div class="row">
        <div class="col-sm-12 email-template-load"></div>
      </div>



      <div class="row">
        <div class="images">
        </div>

      </div>

      <!--div class="email-template-load">

      </div-->
    </div>
    <div class="col-md-3">
      <h5 class="text-info">Members </h5>
      <div class="active-members-list text-success">
      </div >
      <div class="pending-members-list text-danger">
      </div>
    </div>
    <div class="col-md-3">
      <div id='gmaps-canvas'>
      </div>
    </div>
    <div class="row">
      <%#= jwplayer_assets %>
      <%#= jwplayer({file: Marker.last.video.url(:medium)}) %>
      <!-- <iframe src=<%#= Marker.last.pdf.url %> width="600" height="780" style="border: none;"> </iframe> -->

      <!-- <a href="https://docs.google.com/gview?url=#{url}&embedded=true">Your Pdf Viewer</a>  -->
      <%= video_tag Marker.last.video.url(:medium) %>
      <%= link_to 'View Pdf', Marker.last.pdf.url, target: :_blank %>
      <!-- <div id='myElement'>Loading the player ...</div> -->
      <!-- <div class="video"> -->
        <%#= video_tag(Marker.last.video.url,  :size => "320x240", :controls => true, :autobuffer => true) %>
        <%#= videojs_rails sources: { mp4: Marker.last.video.url, webm: Marker.last.video.url}, setup: "{}", :size => "320x240", :controls => true, :autobuffer => true %>
      <!-- </div> -->
    </div>

  </div>
</div>

</body>

app/views/markers/invite.js.erb
$('.email-template-load').html('<%= escape_javascript(render partial: "invitation", locals:{ invitation: @invitation, trip: @trip })%>');

app/views/markers/new.html.erb
<%= render 'form', location: @marker %>

app/views/markers/new.js.erb
$('.modal-body').html('<%= escape_javascript(render partial: "modal", locals:{ trip: @marker })%>');

app/views/markers/partial.js.erb
$("#myModal .modal-body").html('<%= escape_javascript( render partial: "partial1", locals:{ flag: @flag }) %>');
//$('#myModal').modal("show");

app/views/markers/show.html.erb
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

app/views/markers/update.js.erb
console.log('Update');
$('.flash-message').html("<div class='alert alert-success %> alert-dismissible' role='alert'><button class='close' data-dismiss='alert'>×</button><%= flash[:notice] %></div>");